# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8368d631685671d489cd249b6025b4445eb1b55b7b5874272e433bd9d6e6d6f26135a080da115fbd56528c4d7486fd195f40e66dd84d90d1694f8c0617b9b325

test:
  secret_key_base: 2de8be074e4dcbccbe38ed959853c17a9a966017f48da057464df119305f411a0dc629f984beb73d43d06ee1bc2ddd78a27c55ddce67d11fcb93b6fbc5d2b4a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
